files:
  - templatePath: templates/go.mod.txt 
    filePath: ""
    fileName: go.mod
    hasFilePathDomainPrefix: false
    hasFileNameDomainPrefix: false

  - templatePath: templates/gin/main.txt 
    filePath: cmd/api
    fileName: main.go
    hasFilePathDomainPrefix: false
    hasFileNameDomainPrefix: false

  - templatePath: templates/gin/db_tmpl.txt
    filePath: db
    fileName: db.go
    hasFilePathDomainPrefix: false
    hasFileNameDomainPrefix: false

  - templatePath: templates/gin/gorm_db_tmpl.txt
    filePath: db
    fileName: gorm_db.go
    hasFilePathDomainPrefix: false
    hasFileNameDomainPrefix: false

  - templatePath: templates/gin/model_tmpl.txt 
    filePath: models
    fileName: models.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: templates/gin/handler_interface_tmpl.txt 
    filePath: handler 
    fileName: handler.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: false

  - templatePath: templates/gin/handler_tmpl.txt 
    filePath: handler 
    fileName: handler.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: templates/service_interface_tmpl.txt 
    filePath: service
    fileName: service.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: false

  - templatePath: templates/service_tmpl.txt 
    filePath: service
    fileName: service.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: templates/gin/storage_interface_tmpl.txt 
    filePath: storage 
    fileName: storage.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: false
    
  - templatePath: templates/gin/storage_tmpl.txt 
    filePath: storage 
    fileName: storage.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: true

  - templatePath: templates/gin/errors_tmpl.txt 
    filePath: errors 
    fileName: http_error.go
    hasFilePathDomainPrefix: false 
    hasFileNameDomainPrefix: false 

  - templatePath: templates/gin/error_handler_tmpl.txt 
    filePath: middlewares 
    fileName: error_handler.go
    hasFilePathDomainPrefix: false
    hasFileNameDomainPrefix: false

  - templatePath: templates/gin/http_responses_tmpl.txt 
    filePath: responses 
    fileName: http_response.go
    hasFilePathDomainPrefix: false
    hasFileNameDomainPrefix: false

