files:
  - templatePath: gin/model_tmpl.txt 
    filePath: models
    fileName: models.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: gin/handler_interface_tmpl.txt 
    filePath: handler 
    fileName: handler.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: false

  - templatePath: gin/handler_tmpl.txt 
    filePath: handler 
    fileName: handler.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: base/service_interface_tmpl.txt 
    filePath: service
    fileName: service.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: false

  - templatePath: base/service_tmpl.txt 
    filePath: service
    fileName: service.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: gin/storage_interface_tmpl.txt 
    filePath: storage 
    fileName: storage.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: false
    
  - templatePath: gin/storage_tmpl.txt 
    filePath: storage 
    fileName: storage.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: true
