files:
  - templatePath: std/model_tmpl.txt 
    filePath: models
    fileName: models.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: std/handler_interface_tmpl.txt 
    filePath: handler 
    fileName: handler.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: false

  - templatePath: std/handler_tmpl.txt 
    filePath: handler 
    fileName: handler.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: std/handler_http_errors_tmpl.txt 
    filePath: handler 
    fileName: http_error_handler.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: false 


  - templatePath: base/service_interface_tmpl.txt 
    filePath: service
    fileName: service.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: false

  - templatePath: base/service_tmpl.txt 
    filePath: service
    fileName: service.go
    hasFilePathDomainPrefix: true 
    hasFileNameDomainPrefix: true

  - templatePath: std/storage_interface_tmpl.txt 
    filePath: storage 
    fileName: storage.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: false
    
  - templatePath: std/storage_tmpl.txt 
    filePath: storage 
    fileName: storage.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: true

  - templatePath: std/storage_sql_statements_tmpl.txt 
    filePath: storage 
    fileName: sql_statements.go
    hasFilePathDomainPrefix: true
    hasFileNameDomainPrefix: true
